### ISSUE TITLE
Doesn't work with IE9

### ISSUE THREAD

**Issue by stuporglue** [dovy/Pedigree-Viewer#4]
Not sure about other versions of IE. It worked with IE8 at one point, I'm pretty sure.

**Comment by dovy** [comment]
Huh. I thought it worked, but there seems to be a error for IE8 too. Here's what IE8 says:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Timestamp: Mon, 22 Oct 2012 02:35:51 UTC

Message: 'G_vmlCanvasManager' is undefined
Line: 1035
Char: 11
Code: 0
URI: http://tree.sharingtime.com/sharing-time-ui.js

Can you comment the IE9 error? Perhaps it's a simply function declaration.

**Comment by stuporglue** [comment]
Exact same issue on IE9 and in the same place.

**Comment by stuporglue** [comment]
Now works with IE9. We're going to leave IE7/8 behind for now.
