### ISSUE TITLE
Only names and gender are presented. You should be able to see more info

### ISSUE THREAD

**Issue by stuporglue** [dovy/Pedigree-Viewer#6]
Especially when loading info from a GEDCOM, you should be able to select an ancestor and view all the info the GEDCOM has about that ancestor.

**Comment by dovy** [comment]
There's a start to this, but it needs to be built out. How much information should show?

Here are some examples from the industry leaders:

FamilySearch: http://cl.ly/image/2r0W323Q2N28
Munida: http://cl.ly/image/3P340r3d0Q0f
Ancestry: http://cl.ly/image/2c2T1O1v1J43
WeRelate: http://cl.ly/image/242U0i0t041I
MyHeritage: http://cl.ly/image/0O1Y1T3a1105
Geni only has birth/death

For the sleek view I like FamilySearch. For the more bang for your buck view I like Mundia. We could also have various views that are possible. What are your thoughts?

**Comment by stuporglue** [comment]
Fixed with callback ability. Users can code what they want now.
