### ISSUE TITLE
No zoom scrollbar. 

### ISSUE THREAD

**Issue by stuporglue** [dovy/Pedigree-Viewer#8]
Zooming with mouse works. We need a graphical zoom bar for ease of use.

**Comment by dovy** [comment]
That's already built. I'll try to implement shortly.

**Comment by stuporglue** [comment]
Yeah, the image we had before wasn't ours to distribute though, so I removed it before publishing. Should be an easy fix.

**Comment by dovy** [comment]
Very. Another plug to use like jQuery UI or Bootstrap.

**Comment by stuporglue** [comment]
It's already using jQuery UI, so if it's either jQuery UI or Bootstrap, let's stick with just jQuery UI.

**Comment by dovy** [comment]
jQueryUI works with both.  ;)  It's built in sort of.

**Comment by stuporglue** [comment]
Fixed
